server:
  port: 8080


spring:
  application:
    name: demo
  http:
    encoding:
      enabled: true
      force: true
      charset: utf-8
management:
  health:
    redis:
      enabled: true
    rabbit:
      enabled: true
    db:
      enabled: true
    mongo:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true