apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: test
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: demo-default #使用已經命名過的port 8080
      nodePort: 30123
  selector:
    app: demo
    env: dev
