apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-rc
  namespace: test
spec:
  replicas: 2
  selector:
    env: dev
    app: demo
  template:
    metadata:
      labels:
        env: dev
        app: demo
    spec:
      nodeSelector: #調度到具有特定標籤的節點上
        kubernetes.io/hostname: "docker-desktop"
      containers:
        - image: demo:v1 #創建容器所用image
          name: demo #容器名稱
          ports:
            - containerPort: 8080 #容器監聽端口
              protocol: TCP
